### PR TITLE
Add support for 8th

### PR DESCRIPTION
**Pull request by glennj**
Responding to https://discord.com/channels/854117591135027261/1169215168484479006/1169222372566511676

### CODE REVIEW

**Comment by glennj** [comment]
@ErikSchierboom CI not launching for PRs?

**Comment by ErikSchierboom** [comment]
That's weird. I'll look into it!

**Comment by ErikSchierboom** [comment]
Found it. They should be enabled now. Could you add an empty commit or something to test?

**Comment by glennj** [comment]
"8th" broke it, starting with a digit

**Comment by glennj** [comment]
Lots of checks getting cancelled, lots failing.
Do we really need to run on so many architectures? Surely the Exercism infrastructure is only using one specific build.

**Comment by ErikSchierboom** [comment]
> Do we really need to run on so many architectures? Surely the Exercism infrastructure is only using one specific build. 

We don't. I'll update tomorrow. It's just that I want to make as few changes as possible to the original code, for easy of updating this fork from its source. I might disable these workflows and then add a new one that's specific to this repo.

**Comment by ErikSchierboom** [comment]
See https://github.com/exercism/tokei/pull/5#pullrequestreview-1709569177

**Comment by ErikSchierboom** [comment]
@glennj CI is failing

**Comment by glennj** [comment]
@ErikSchierboom and now CI not running?

**Comment by ErikSchierboom** [comment]
@glennj I had merged master into this branch, but it looked like those commits were gone in this branch.

**Comment by glennj** [comment]
Phew, that was a journey!

**Comment by ErikSchierboom** [comment]
You won though! Let me try this :)

**Comment by ErikSchierboom** [comment]
We're re-counting the existing 8th submissions' lines of code right now.

**Comment by ErikSchierboom** [comment]
Processing done. For fun, I did a quick count. The following hash shows num_loc => num_submissions

{1=>134,
 2=>78,
 3=>252,
 4=>30,
 5=>36,
 6=>24,
 7=>20,
 8=>16,
 9=>13,
 10=>19,
 11=>13,
 12=>25,
 13=>16,
 14=>7,
 15=>13,
 16=>6,
 17=>8,
 18=>14,
 19=>10,
 21=>10,
 22=>2,
 23=>10,
 24=>2,
 25=>6,
 26=>2,
 27=>4,
 28=>4,
 29=>2,
 30=>5,
 31=>7,
 32=>5,
 33=>1,
 34=>3,
 35=>2,
 36=>2,
 37=>2,
 38=>5,
 41=>2,
 42=>2,
 43=>1,
 45=>1,
 46=>2,
 49=>1,
 50=>4,
 52=>2,
 53=>1,
 54=>1,
 55=>2,
 57=>1,
 62=>1,
 63=>4,
 69=>3,
 83=>1,
 92=>2,
 94=>3}

**Pull request merged**
